name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          echo "[tool.poetry]" >> pyproject.toml
          echo "package-mode = false" >> pyproject.toml
          poetry install --with dev --sync

      - name: Run Djando tests with coverage
        run: |
          poetry run pytest devpro --cov=devpro --cov-fail-under=82