name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Comando de sucesso
        run: ls /
      - name: Comando de erro
        run: ls /não/existe


